services:
  - type: web
    name: kothabarta-backend
    env: node
    rootDir: server
    buildCommand: npm ci && npm install --save-dev @types/express && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
